main: principal.QuestionsPlugin
version: 1.4.0
name: questions
author: lsEmpty
api-version: 1.13
description: This plugin is a chat game that runs every X amount of time.

commands:
  qtop:
    description: Get top 10 players with the most questions answered
  qsave:
    description: Save player data
  qreload:
    description: Reload questions data or config data
  qhelp:
    description: Show all commands of this plugin
  qenable:
    description: In case the plugin is not working, start the thread
  qdisable:
    description: In case the plugin is working, stop the thread

permissions:
  questions.admin:
    description: The user with this permission can use admin commands.
    default: op
    children:
      questions.user: true
  questions.user:
    description: Allows the user can use normal commands # qtop and qtop <user>
    default: true